### ISSUE TITLE
Expensive SMA connectors

### ISSUE THREAD

**Issue by sebgus** [jankae/LibreCAL#16]
Considering this design only goes up to 6 GHz, why not use cheaper SMA connectors?

E.g. the Linx CONSMA003.062 (18 GHz, €4) vs Amphenol 901-10510-2 (26.5 GHz, €11.5).

**Comment by sebgus** [comment]
My apologies, I saw now that the return loss on the Amphenol connector is very good.

Maybe the 50 Ohm termination resistor could be replaced by a 0201 50 Ohm or two 0402 100 Ohm resistors in parallel to improve the design further? At 6 GHz the impedance of a regular 0402 50 Ohm could be as high as 60 Ohm due to parasitic inductance.

**Comment by jankae** [comment]
Yes, I selected these connectors due to their good return loss (and the easy transition to GCPW in the layout due to the small center pin). 
Maybe a 0201 termination resistor could improve things, but I have managed to get 20dB return loss with a 0402 as well and the additional return loss from the switches (and the layout surrounding them) dominate the return loss anyway. I don't think any significant return loss improvements are possible by adjusting the resistor.

But then again, this project is still in an early prototype state (I got distracted by other things for a while now), so I haven't done an extensive evaluation.
