### ISSUE TITLE
LibreCAL-GUI Coefficient -> Load From Device crash at end

### ISSUE THREAD

**Issue by bvernoux** [jankae/LibreCAL#17]
How to reproduce the issue:

- When we have some coefficients in LibreCAL and we call in LibreCAL-GUI `Coefficient -> Load From Device` we have an application crash at end of the coefficient loading

This issue is triggered when `appwindow.cpp AppWindow::loadCoefficients()` => call the code `delete d;` due to the fact some threads are not finished and report updated progress ... to QProgressDialog and it is deleted.

- Quick fix for that is to avoid doing `delete d;` and create the QProgressDialog only one time (and destruct it when closing the application)

**Comment by jankae** [comment]
Thank you very much for tracking down the issue. I couldn't replicate it and think the code should be working because all connected lambdas that are handling code for ```d``` also have ```d``` as the receiver for the slot. This should prevent the slot from being executed after ```d``` has been deleted.
But maybe I did miss something and depending on the thread timing it can still crash. I also think your proposed solution is an easy way to avoid this problem altogether, so I implemented it with 0ccba625
Please let me know if this fixes the crash for you.
