### ISSUE TITLE
Question about low frequency performance of the PE426462

### ISSUE THREAD

**Issue by miek** [jankae/LibreCAL#20]
Hi,

I'm looking to build a LibreCAL for myself and, looking through the bill of materials, I noticed that the PE426462 switch is only specified down to 10 MHz despite the overall project going down to 9 kHz. I wonder if that is an error, or do you find that the switch performs well at lower frequencies anyway despite its specs? Would you be able to share S-parameters for any prototypes, just to get an idea of how it performs?

Thanks!
Mike

**Comment by jankae** [comment]
Yes, the PE426462 is used beyond its spec here. In my experience this is usually possible with a lot of switches and some tests have confirmed this so far. And of course I might adjust the spec if it turns out that 9 kHz was a bit too optimistic. Here are example measurements from a LibreCAL prototype:
[ExampleCoefficients.zip](https://github.com/jankae/LibreCAL/files/13932879/ExampleCoefficients.zip)
They are not ideal for this question because they cover 9 kHz to 8.5 GHz with only 1001 points -> frequency steps are too wide to really cover the region of interest between 9 kHz and 10 MHz. Also, ignore P2_SHORT which is obviously wrong (seems to be an OPEN, likely some issue with my prototype)

**Comment by cstarkjp** [comment]
Would the PE42562 switch work? It spans 9kHz-8GHz. It's _almost_ pin compatible – just pin 7 VSS_EXT is different.

**Comment by jankae** [comment]
Thanks for the partnumber, that could be a good alternative if the original part would degrade performance below 10 MHz too much (although it is a bit more expensive). I think this would even be completely pin compatible: Pin 7 of the PE426462 is GND and if you connect VSS_EXT to GND on the PE42562, it is using its integrated negative voltage generator.

**Comment by miek** [comment]
Thanks! Sounds like it works well despite the spec so I'll go ahead and try it out, and report back if I have any interesting test results.
I was considering the PE426462 too, but it seemed to be quite a lot more expensive so it'd be nice to avoid if possible.
