### ISSUE TITLE
GCPW dimensions don't match the net class specs due to zone clearance

### ISSUE THREAD

**Issue by miek** [jankae/LibreCAL#21]
I noticed that the GCPW is specified as 0.295/0.2mm trace/space (which is very to close to JLC's calculator), but in practice it comes out differently because the zone clearance is set to 0.36mm. I'm not sure if that'll cause a big difference and clearly it's worked so far, but I thought I'd just let you know.

I'm planning to go ahead and get boards with the 0.295/0.2 spec and I'll post TDR/VNA measurements when I get them.

**Comment by jankae** [comment]
Yep, you are right that there is a difference to what the calculator says. I guess the data in the KiCad files is a bit confusing because of these PRs: #2 and #8

What I have observed experimentally is that the originally chosen width and distance (0.3mm and 0.36mm) works very well in the LibreVNA. #2 changed the trace width to 0.295 which I didn't mind (such a small change). I didn't merge #8 because I wanted to keep the distance to GND at 0.36mm (despite the calculator saying this is wrong). In the end it doesn't really matter here (at least in my opinion):
- traces are very short
- errors from transitions to connectors/switch ICs will dominate reflections and losses (never mind the inherent FR4 losses)
- the calibration standards are far from ideal anyway and this will be compensated for by the calibration coefficients

It really comes down to me being unwilling to change a proven and working design. Getting consistent trace impedances on FR4 is always a bit of a gamble.

**Comment by miek** [comment]
Ah right, I didn't realise that the net class was introduced in those PRs and I was also confused because 0.18mm spacing was mentioned as the intended value previously, but if 0.36mm was intended then fair enough!
