### ISSUE TITLE
Update LibreCAL-GUI & firmware version to v0.1.1

### ISSUE THREAD

**Issue by bvernoux** [jankae/LibreCAL#7]
I see you have pushed some precious fixes / improvements in latest LibreCAL-GUI & LibreCAL firmware commit from Jan 23 & 24, 2023 but unfortunately the LibreCAL-GUI & firmware version have not changed and they are still v0.1.0
It will be great to update them to 0.1.1 to avoid confusion with previous firmware/LibreCAL-GUI ...

LibreCAL-GUI change:
- https://github.com/jankae/LibreCAL/commit/1f512ad95bb842af440e329ada94a683d7dc7734 "Fix expected *IDN? response"

LibreCAL firmware changes:
- https://github.com/jankae/LibreCAL/commit/2410e343ae689072236260943ba30a07f0889d49 "SCPI API adjustments"
- https://github.com/jankae/LibreCAL/commit/b41dedec7b12fbbe7c6b08205d45196db9a4527e "Allow higher I term for temperature control in colder environments"

Especially the firmware change https://github.com/jankae/LibreCAL/commit/b41dedec7b12fbbe7c6b08205d45196db9a4527e
- With that change it improve a lot the time to reach the 35°C temperature when the board is quite cold <= 20°C (or even outside case)

**Comment by jankae** [comment]
I don't really intend to increase the version number for small changes in commits. I will however increase the version number for every release. Since this project does not have any releases yet (still in prototype stage), it is still at the starting version number of 0.1.0

The LibreCAL-GUI also shows the commit hash when checking the version, so there shouldn't be any confusion there. And if you have a different firmware than from a official release you must have either compiled it yourself or downloaded it from the action tab of the repository - in both cases I assume you know enough about what you are doing and specifically want a development version of the firmware that hasn't been released yet (and doesn't have a unique version number).
